### ISSUE TITLE
Rack v1: Menu names move around when knob is turned

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1215]
OS: Win 10, **4K screen**
Rack: `v1`, 9c9daedcd967c6ae6cb2bfe79ae92ca26d69fdec

![vcvrack_menu_wiggle](https://user-images.githubusercontent.com/624427/53603274-31d51400-3b6e-11e9-826f-89d1fa73e4cf.gif)

**Comment by synnys** [comment]
I had this too under macOS.

**Comment by AndrewBelt** [comment]
This is caused by the NanoVG state not being reset by the FramebufferWidget during `step()`. I thought this was fixed since `nvgReset()` was added after drawing the framebuffer, and I can't reproduce it now. But regardless, I've added yet another right before the scene's `draw()` call in ffb9e4b. Can both of you confirm this fixes it?

**Comment by cschol** [comment]
Still occurs for me with this latest change:

![vcvrack_menu_wiggle_2](https://user-images.githubusercontent.com/624427/53927117-0016ee00-4043-11e9-9151-29b58f93b2c8.gif)

**Comment by cschol** [comment]
This seems to be fixed in the latest version of Rack. Closing.
