### ISSUE TITLE
Fundamental plugins don't build any more in Ubuntu (and neither do mine)

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1583]
Since the namespace change I have not been able to build anything on linux.

Always get error about `rack` being ambiguous. like this:
```
 error: reference to ‘rack’ is ambiguous
 #define APP rack::appGet()
```
I "fixed" all my stuff by using `::rack` instead of rack (and ::rack::App, etc). But I can't fix the macros that use the unqualified rack namespace, so DEFER, WARN, etc have to be be removed from my code base.

I thought it was just something odd about my code, but if Fundamental doesn't build....

**Comment by squinkylabs** [comment]
btw, I've communicated with three others, and we all have this issue. I've patched my repo, so it actually builds now.

**Comment by AndrewBelt** [comment]
This seems to be an issue with older compilers. I've removed `namespace rack = rack;` in 4bc44cf. The following plugins need to be repaired by replacing `rack::APP`, `rack::DEBUG`, `rack::INFO`, `rack::DEFER`, etc with the non-`rack::` versions.
- squinkylabs-plug1
- BaconMusic
- Bogaudio
- HetrickCV
- DHE-Modules

**Comment by squinkylabs** [comment]
thanks! btw, we may have "old compilers", but they are the ones you get with the LTS versions of Ubuntu updated with `apt-get`

**Comment by AndrewBelt** [comment]
One of these days, I'll provide a Docker container with GCC 9 that links to libc 2.23 and statically links to libstdc++.

**Comment by squinkylabs** [comment]
btw, don't know why, but APP still doesn't work in my code on my old compiler. using `::rack::appGet()` instead. rack is still ambiguous in my code base, although ::rack of course is not.

**Comment by AndrewBelt** [comment]
Post the error output.

**Comment by squinkylabs** [comment]
Already "fixed it". all the macros (APP, DEFER, WARN) fail with " rack is ambiguous". So now all my code uses ::rack::foo, and there are no instances of rack::foo any more.

**Comment by squinkylabs** [comment]
But I just tried the impromptu plugins, and they still fail, too:

```../../include/app.hpp:52:13: error: reference to ‘rack’ is ambiguous
 #define APP rack::appGet()
```

**Comment by squinkylabs** [comment]
So whatever sin I committed long ago make is so rack (without the ::rack) is ambiguous on many linux installs. The only place this is a problem is with the macros like APP, WARN, DEFER. So I have a relatively simple solution - I don't use these. I have my own copy that fully qualifies the namespace. The only problem is I forget about this, and WARN or INFO show up in my repo and some Linux user can't build any more.

Would it be possible to fully qualify those namespaces in your macros?

**Comment by AndrewBelt** [comment]
I don't understand. There's no ambiguous namespace after 4bc44cf. The macros already use fully qualified namespaces after dbd117ea62a1529bc43fd74c4484d1369f0e4691. What's the issue still?

**Comment by squinkylabs** [comment]
current code is:
```c++
#define WARN(format, ...) rack::logger::log(rack::logger::WARN_LEVEL
```
to make that work, I do this:

```c++
#define sqWARN(format, ...) ::rack::logger::log(::rack::logger::WARN_LEVEL
```

**Comment by AndrewBelt** [comment]
Why is `::` needed before `rack`? Please post the entire error message.

Are you compiling "norbert" with an old SDK? Can you post the version/commit of the SDK you're using?

**Comment by squinkylabs** [comment]
Norbert a person - "news of the rack". I'll try to get more info. Or see if I can bring back the messages on my linux - I think I can...

**Comment by squinkylabs** [comment]
Here's the full error. I'm wondering if it's still about places in my code where I don't include rack.hpp, but (in this case) seem to be including logger.h by itself. I'll try "fixing" that and see if the problem goes away.
```
g++  -std=c++11 -Wsuggest-override -I./dsp/generators -I./dsp/utils -I./dsp/filters -I./dsp/third-party/falco -I./dsp/third-party/kiss_fft130  -I./dsp/third-party/kiss_fft130/tools -I./dsp/third-party/src -I./dsp/third-party/midifile -I./sqsrc/thread -I./dsp/fft -I./composites -I./sqsrc/noise -I./sqsrc/util -I./sqsrc/clock -I./sqsrc/grammar -I./sqsrc/delay -I./midi/model -I./midi/view -I./midi/controller -I./util -I./src/third-party -I.src/ctrl -I./src/kbd -D __V1x -D _SEQ -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -D NDEBUG -D __PLUGIN -c -o build/src/kbd/SqKey.cpp.o src/kbd/SqKey.cpp
In file included from ../../include/common.hpp:2,
                 from ../../include/rack.hpp:4,
                 from src/kbd/../ctrl/SqHelper.h:8,
                 from src/kbd/KeyMapping.cpp:4:
src/kbd/KeyMapping.cpp: In constructor ‘KeyMapping::KeyMapping(const string&)’:
../../include/logger.hpp:13:27: error: ‘logger’ has not been declared
 #define INFO(format, ...) logger::log(rack::logger::INFO_LEVEL, __FILE__, __LINE__, format, ##__VA_ARGS__)
                           ^~~~~~
src/kbd/KeyMapping.cpp:58:5: note: in expansion of macro ‘INFO’
     INFO("parsing key mapping: %s\n", configPath.c_str());
     ^~~~
make: *** [../../compile.mk:61: build/src/kbd/KeyMapping.cpp.o] Fehler 1
make: *** Auf noch nicht beendete Prozesse wird gewartet …
```

**Comment by AndrewBelt** [comment]
That's an old version of the SDK. He needs to use the SDK after 4bc44cf, since you are take advantage of that fix in your code. I can't fix already-released SDKs.

**Comment by squinkylabs** [comment]
ah! tx. no problem, I'll get him to pull a new one. tx again!
