### ISSUE TITLE
Menu bar is invisible, screen renders with vertical offset

### ISSUE THREAD

**Issue by Mistermoleymole** [VCVRack/Rack#369]
OS (if applicable):windows 10 64bit up to date
Version (or "dev" if compiling from source): 0.4.0 downloaded zip file extracted and running exe.

Running on a dell xps13 on both external monitor and it's own screen(1920x1080) all I can see is the top windows bar, then direct under that is the top rack bar. 

Let me know if you need any further info

Cheers

**Comment by AndrewBelt** [comment]
Screenshot?

**Comment by Mistermoleymole** [comment]
I have also now tried compiling the application, and running but that made no differnece

![image](https://user-images.githubusercontent.com/33511958/32626955-c2586656-c588-11e7-92d6-323750d4ad5d.png)

**Comment by Mistermoleymole** [comment]
I also seem to get mouse pointer issues where a loty of the time the actual position of the pointer is below where it will actually click within the software window.

**Comment by AndrewBelt** [comment]
Weird! I have no idea why it could be doing that!
The toolbar must exist, so it is hidden underneath the rack, otherwise a segfault would occur in `RackScene::step()`, and on line https://github.com/VCVRack/Rack/blob/master/src/app/RackScene.cpp#L45 the position of the rack is set from the height defined https://github.com/VCVRack/Rack/blob/master/src/app/Toolbar.cpp#L100

**Comment by Mistermoleymole** [comment]
Hi Andrew, Is there a way i can get a copy of the older version to try, so i can see if its a version thing or its something to do with my laptop?   This is the first time I've ever tried to use your application so have never tried an earlier build.

Cheers

**Comment by AndrewBelt** [comment]
Sure, just change the download URL from 0.4.0 to 0.3.2 or 0.3.1.

**Comment by Mistermoleymole** [comment]
ok.. eventually got round to doing this. Tried all versions, all the same, so not a version issue.   Could it be the fact its only a 1080 screen?  Is there a certain res screen needed?

**Comment by bolognam** [comment]
Same issue on xps 15 9560 with a 1080p screen. My desktop with a 1440p screen seemed to work just fine however it doesn't have the creator's update like my laptop.

**Comment by AndrewBelt** [comment]
Is anyone using the dev version?

**Comment by http404error** [comment]
Same issue here (mouse offset, no toolbar) with 100% consistency.

Running Windows 10, Dell XPS 15 9550, 1080p laptop.

On 0.5.0 right now (issue occurred on 0.4.0 also) but I'll try dev when I get the time. I'm a software professional so I'm willing to dive in and help debug if you want to sync up.

**Comment by Nic-Mendoza** [comment]
Exactly the same hardware and issues as http404error.  Will test on different h/w tomorrow.

**Comment by AndrewBelt** [comment]
@http404error If you can get the build working, I'll pass some patches/edits back and forth.

**Comment by Mistermoleymole** [comment]
@bologna hi mate.... Have you tried plugging your laptop into your desktop screen? Wondering if it's the laptop or the limited 1080 display that could be the issue?

**Comment by bolognam** [comment]
I don't have access to that monitor until Monday but I'll try it out then and let you know.

**Comment by Mistermoleymole** [comment]
@bolognamthatbwould be great. Cheers.

**Comment by AndrewBelt** [comment]
Here's a build of a17ae2c6cc80882ed3ef7ff926dfa685786b03dc using OpenGL 3.2 instead of OpenGL 2.0. Someone give it a try and report back?
https://andrewbelt.name/files/VCV/Rack-0.5.0-mac.dmg

**Comment by AndrewBelt** [comment]
Ah right, posted on the wrong thread. But I prepare Windows builds here anyway.

**Comment by Mistermoleymole** [comment]
God damn it! I got all excited then! :D :)

**Comment by bolognam** [comment]
No dice. Both "extend these displays" and "show only on 2" options in Windows with an external 1440p display didn't fix the issue in version 0.5.0. This is still with the Creator's Update. I'll try the same things once Andrew puts out the Windows build. Additionally, I've updated to version 0.5.0 on my desktop and it still works fine; however, I haven't updated my desktop to the Creator's Update yet.

**Comment by Mistermoleymole** [comment]
@bolognam oh well, good test though.  Means it must be something to do with the xps graphics rather than the fact its using a 1080p display.

**Comment by Mistermoleymole** [comment]
A guy i work with has just bought one of the new xps 15s.  And he says his works fine.  Is everyone here on the latest or a previous model of the xps? Mines a xps13 9350

**Comment by citizenknet** [comment]
hi, i just got a new xps 15 (4k) and is also doing the same - no file menu and right click/add items is shifted so, mouse needs to be below what you select. hopefully we can figure out what is causing the issue. I tried creating manifest file so, wouldn't default to crazy small on 4k monitor and also, updated all the dell chipset/graphics/bios... still no go.

**Comment by citizenknet** [comment]
btw,, mine has the nvidia gforce gtx 1050 not intel card inside..

**Comment by Nic-Mendoza** [comment]
Here's my summary system and
[XPS Sys Info.txt](https://github.com/VCVRack/Rack/files/1513055/XPS.Sys.Info.txt)
 full display info from an XPS experiencing these issues if it helps anyone fix.

**Comment by AndrewBelt** [comment]
Great! There are two reasons the rack widget is at position (0, 0) from the top left of the screen. Either its box position is changed by something, or nanovg / OpenGL is not transforming correctly. Since the mouse clicks seem to be offset correctly but the rack widget is being drawn 31 pixels too high, I think it's the latter, but let's rule out the first. Add

```cpp
	Vec offset = gRackWidget->getAbsoluteOffset(Vec(0, 0));
	debug("%f %f", offset.x, offset.y);
```
to RackScene::step() in RackScene.cpp.

**Comment by http404error** [comment]
0.00
31.00

So, as expected, not that.

**Comment by bologna** [comment]
I think I might inadvertently be on this thread. Probably another bologna
you're looking for.

**Comment by AndrewBelt** [comment]
Okay, now let's test whether `nvgTranslate()` works at all. Place

```cpp
	Button *b = new Button();
	b->box.pos = Vec(100, 100);
	b->box.size.x = 200;
	b->text = "hello";
	addChild(b);
```

at the end of `RackScene::RackScene()` in RackScene.cpp and see if a button appears at the origin or at (100, 100), or not visible at all.

**Comment by http404error** [comment]
The button appears at, um, what looks like around (100, 69). Almost like it's measuring from the corner of the title bar.

![image](https://user-images.githubusercontent.com/2876044/33465504-0e502c68-d5fd-11e7-9a3d-799cf5f97439.png)

**Comment by Mistermoleymole** [comment]
Unfortunately I don't have the skills to work out what's happening here, but just wondering if anyone's any closer? Cheers all.

**Comment by http404error** [comment]
When I get some free time I will experiment a little with debugging it on
my own, but so far there is no fix available yet, sorry.

**Comment by citizenknet** [comment]
FYI everyone with XPS laptops... just upgraded the new BIOS and chipset dated Dec 12 @ support.dell.com and now all is working. Toolbar/filemenu/login appears and no offset on menu items!!!

**Comment by Nic-Mendoza** [comment]
Dell Support auto detect doesn't offer a Dec 12 BIOS or chipset and the issue remains with my XPS 15 9550 currently on BIOS Version 1.3.0 11/08/2017.  What version have you got working?

**Comment by citizenknet** [comment]
It appears that this may be available for the XPS 15 9560 only then.
it is dated on the website as Dec 12 release.
BIOS  Version is 1.6.2 11/12/17
Filename is XPS_15_9560_1.6.2.exe

**Comment by Nic-Mendoza** [comment]
Thanks. I'll try take this up with Dell Support to see:
1.  What was included in the update that might have fixed the issue.
2. Whether a corresponding update is going to be ported to a 9550 BIOS
3. Whether version 1.6.2 is OK to apply to a 9550

**Comment by lanthias** [comment]
FWIW I have the same issue (Dell XPS 13) and I updated my BIOS and chipset as per above instructions but it hasn't seemed to resolve it.

Also, I have a 0.4.0 version lying around which _used_ to work correctly, and now when I open that I have the same issue.

**Comment by bologna** [comment]
Can you guys take me off of this list? Not sure why I'm on it. Thanks!

**Comment by AndrewBelt** [comment]
@bologna I think @Mistermoleymole mis-tagged you in this post https://github.com/VCVRack/Rack/issues/369#issuecomment-346890217 so go to https://github.com/VCVRack/Rack/issues/369#issuecomment-353983768 and click Unsubscribe on the sidebar.

**Comment by bitquisite** [comment]
Hi, unfortunately, same issue here on an XPS 15 9550, even with the latest BIOS update (1.6.1., 11-Dec-17), thanks!

**Comment by Nic-Mendoza** [comment]
Have you tried setting Rack.exe to use the NVIDIA processor as preferred through the NVIDIA Control panel? This worked for me.

**Comment by bitquisite** [comment]
Indeed, this works! Thank you so much!

**Comment by mcmonkeys1** [comment]
I have Dell XPS 9560, same issue: mouse off at top of screen, better at bottom.
Upgraded BIOS with Dec 2017 release, all good now.

**Comment by OldGregg570** [comment]
Was having the same issue on my Dell Precision 5510. Solved by upgrading my video drivers which installed Nvidia Control Panel. I am now able to right click "Rack.exe" and select "Run with graphics processor" to choose which GPU to use.

**Comment by themotherland** [comment]
Currently having this issue on an HP spectre x360. Upgraded my bios and it hasn't worked. Im unable to run it with nvidia control panel due my laptop having chipset graphics. pls help

**Comment by jhcitteam** [comment]
Same issue on Lenovo X270 running Window 10 64-bit Version 1709 build 16299.492

**Comment by joshcann** [comment]
Same issue on Lenovo X270 Windows 10 64-bit Version 1709 build 16299.492

**Comment by http404error** [comment]
Couple updates. Nic Mendoza's workaround helped me, but of course that doesn't help users without alternative graphics cards. I found another piece of software that suffers from the same issue (LackeyCCG). I'm fairly certain that it's a bug in the graphics driver for integrated graphics on Windows 10. It might be related to the gui framework or method used but I haven't looked into that avenue much yet.

**Comment by AndrewBelt** [comment]
Can all the people who have posted their laptop model post their graphics card model? That's the relevant hardware for this issue. I believe everyone has an Intel HD3000/4000.

**Comment by bitquisite** [comment]
Hi Andrew,
my laptop model is Dell XPS 15 2016 - the problem exists when using its Intel HD 530 card (default) and disappears after switching to its NVIDIA GeForce GTX 960M card.
Thanx for everything!
Cheers.

**Comment by http404error** [comment]
I have the same hardware as bitquisite just posted.

**Comment by joshcann** [comment]
Intel HD 620

**Comment by nykwil** [comment]
Having this issue and strangely have the exact configuration as bitquisite and http404error.

**Comment by dburgan** [comment]
FYI - I was experiencing this problem as well.  But it seems fixed now, by updating video drivers.

I'm using Windows 10 with Intel Garphics and just went into the Device Manager, right clicked on the Intel Graphics device, and clicked Update Driver.  It asked me where to find the update, and I just told it to search the internet.  After downloading/installing, VCV Rack is now rendering correctly on my screen.  So this may have been a bug in the Intel Graphics driver, not VCV Rack.  Other folks should try this as well.

**Comment by nykwil** [comment]
This fixed my problem.  Thanks.

**Comment by joshcann** [comment]
Updating driver from device manager resolved it for me too (HD 620) - weird because I'd already run Lenovo System Update and Intel Driver & Support Assistant and both said I was up to date...yet device manager found something newer and it fixed the missing toolbar.

**Comment by nykwil** [comment]
Dell also said my laptop driver's were up to date.

**Comment by AndrewBelt** [comment]
Closing, since I haven't heard this issue for Rack 1.0.0+. Comment if it hasn't been fixed.

**Comment by AndrewBelt** [comment]
Reopening because someone has reported an issue about this.

**Comment by alagoa** [comment]
This problem seems to be related with some Intel drivers.
If you have Intel+NVIDIA, it is probably running on Intel, running it with the NVIDIA ones "solved" it for me.

**Comment by nykwil** [comment]
XPS 15 updated the Intel video drivers fixed this.
