### ISSUE TITLE
Program Crash on Module Deletion

### ISSUE THREAD

**Issue by fracturedface** [VCVRack/Rack#378]
OS (if applicable): MacOS 10.12.6 (16G29)
Version (or "dev" if compiling from source): dev

This is a odd bug. Whenever I go to delete modules in VCV the program will sometimes crash. Mass deleting modules by holding down delete and moving my cursor around exhibits the same behavior, but only sometimes. I've notice this with all modules and it makes deleting a pain.

I can't seem to find a pattern anywhere though.

**Comment by AndrewBelt** [comment]
I've been able to produce this twice, so it's very weird. I've been running Rack exclusively in a debugger since then, but you are not alone.

**Comment by antoniograzioli** [comment]
it happened to me as well, but almost randomly...

**Comment by AndrewBelt** [comment]
Until we find the cause, run `make debug` instead of `make run ` and report a backtrace if it crashes!

**Comment by antoniograzioli** [comment]
ok thanks. as I said, it happens a few time but mostly randomly...

**Comment by fracturedface** [comment]
@AndrewBelt I just recompiled about two hours ago and am still experiencing this issue. I've seen this error only:
`make: *** [run] Segmentation fault: 11`

It's gotten pretty annoying, especially with the dialog box that you can "report issues to Apple" with popping up every time.

**Comment by fracturedface** [comment]
Another Update, I think this has something to do with keyboard commands, and repetitive commands specifically.

Using the notes module, typing too much text crashes rack now, and

**Comment by fracturedface** [comment]
Accidentally closed this.

I noticed this issue again today, using the notes module. Gave me the same `make: *** [run] Segmentation fault: 11` error when typing, but only when I pressed `enter` or `backspace` with text in the box. With no text it seems stable.

Maybe something with keyboard input is causing an issue?

**Comment by Nowhk** [comment]
Still happens also to me! Windows 10. Every time I delete a module with keyboard, it crashes.
Right click-> delete works.
Pressing delete or backspace: crash!!!

Always, not "sometimes". Is there any trace that I can post to help on this problem?

**Comment by AndrewBelt** [comment]
@fracturedface  No, that is a different issue #435 

@Nowhk No stack trace is needed. I am able to reproduce this. I do not know the offending code yet though.

**Comment by Nowhk** [comment]
Ok. Hope you can resolve it ;) Thanks

**Comment by fracturedface** [comment]
Any update on this? It gets pretty annoying.

**Comment by AndrewBelt** [comment]
No, but adding to v0.6 milestone since it needs to be fixed.

**Comment by fracturedface** [comment]
Good to know, thanks!

**Comment by AndrewBelt** [comment]
I believe this has been fixed by 6455c1f
Could everyone check this out, create tons of modules, and confirm that no crashes happen anymore?

**Comment by darloth** [comment]
Not certain it's the same issue but I believe I'm still getting this on windows 10.

It only appears to happen when I add a large variety of different modules, and seems to be especially sensitive to large modules with lots of knobs and/or other interface elements, but I am finding it very difficult to reliably reproduce.  There was nothing useful in the log when it occurred.

**Comment by unlessgames** [comment]
I'm having something similar. (currently at 002cae0 running on linux)
I have a .vcv file where if I delete any of 2 ADSRs with delete/backspace it crashes everytime, but if I delete/add different modules before then it doesn't.
make debug gives:
`
Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
0x0000555555757e39 in rack::cursorPosCallback (window=<optimized out>, ypos=<optimized out>, xpos=<optimized out>) at src/window.cpp:211
211					gHoveredWidget->onMouseLeave(e);
`

**Comment by fracturedface** [comment]
*Wrong button AGAIN.*

**Comment by AndrewBelt** [comment]
Probably fixed in c999df2 in the v1 branch. Comment if still not present.

**Comment by catronomix** [comment]
This is the main reason I can't use Rack for live purposes as it sometimes also happens when right clicking -> delete :(
I can't wait for v1 >_<
